export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const ERROR_ARTICLES = 'ERROR_ARTICLES';
export const GET_USER_DATA = 'GET_USER_DATA';
export const AUTH_FLAG = 'AUTH_FLAG';
export const EDIT_PROFILE_FLAG = 'EDIT_PROFILE_FLAG';
export const ARTICLE_AUTHOR_DATA = 'ARTICLE_AUTHOR_DATA';